name: tundr
description: tundr clean up removing support for web. Now only supports the android platform.

version: 0.1.11+14

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.2
  firebase_auth: ^0.15.2
  firebase_storage: ^3.0.10
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.2
  provider: ^3.2.0
  image_picker: ^0.6.2
  image_cropper: ^1.1.2
  cached_network_image: ^2.0.0
  flutter_image_compress: ^0.6.3
  flutter_video_compress: ^0.3.7+8
  permission_handler: ^4.0.0
  intl: ^0.16.0
  uuid: ^2.0.4
  animator: ^1.0.0+3
  fl_chart: ^0.6.1
  video_player: ^0.10.6
  photo_view: ^0.9.2
  http: ^0.12.0+4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: assets/images/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttc
