name: tundr
description: tundr clean up removing support for web. Now only supports the android platform.

version: 0.1.11+14

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.4
  firebase_storage: ^5.1.0
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.3
  provider: ^4.3.2
  image_picker: ^0.6.2
  image_cropper: ^1.1.2
  cached_network_image: ^2.0.0
  flutter_image_compress: ^0.6.3
  flutter_video_compress: ^0.3.7+8
  permission_handler: ^5.0.1+1
  intl: ^0.16.0
  uuid: ^2.0.4
  animator: ^1.0.0+3
  fl_chart: ^0.6.1
  video_player: ^0.10.11+2
  photo_view: ^0.9.2
  http: ^0.12.0+4
  cloud_functions: ^0.7.1
  feature_discovery: ^0.12.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.15.5
  flutter_launcher_icons: ^0.7.4
  pedantic: ^1.9.2
  mockito: ^4.1.3

flutter_icons:
  image_path: assets/images/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    # - family: Helvetica Neue
    #   fonts:
    #     - asset: assets/fonts/HelveticaNeue.ttc
    - family: Liberation Sans
      fonts:
        - asset: assets/fonts/LiberationSans-Regular.ttf
        - asset: assets/fonts/LiberationSans-Italic.ttf
          style: italic
        - asset: assets/fonts/LiberationSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/LiberationSans-BoldItalic.ttf
          weight: 700
          style: italic
