name: tundr
description: tundr clean up removing support for web.

version: 0.2.6+22

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  camera: ^0.7.0+2
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.1
  feature_discovery: ^0.12.1
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.2+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.1.0
  fl_chart: ^0.6.1
  flutter_image_compress: ^0.6.3
  http: ^0.12.0+4
  # image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  intl: ^0.16.0
  photo_view: ^0.9.2
  provider: ^4.3.2
  sentry_flutter: ^4.0.4
  uuid: ^2.0.4
  video_compress: ^2.1.1
  video_player: ^1.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  integration_test: ^1.0.0
  mockito: ^4.1.3
  path_provider: ^1.6.24
  pedantic: ^1.9.2
  test: ^1.15.5

flutter_icons:
  image_path: assets/images/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/test_images/

  fonts:
    - family: Liberation Sans
      fonts:
        - asset: assets/fonts/LiberationSans-Regular.ttf
        - asset: assets/fonts/LiberationSans-Italic.ttf
          style: italic
        - asset: assets/fonts/LiberationSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/LiberationSans-BoldItalic.ttf
          weight: 700
          style: italic
