PETS = ['Cat', 'Dog', 'Serpent', 'Hamster', 'Donkey', 'Fish', 'Tarantula']
STAR_SIGNS = ['Aquarius',
              'Pisces',
              'Aries',
              'Taurus',
              'Gemini',
              'Cancer',
              'Leo',
              'Virgo',
              'Libra',
              'Scorpio',
              'Sagittarius',
              'Capricorn']
RELIGIONS = ['Christianity', 'Buddhism', 'Hinduism', 'Islam']
INTERESTS = [
    'Animals',
    'Bird Watching',
    'Birds',
    'Cats',
    'Dogs',
    'Exotic Pets',
    'Fish',
    'Pets',
    'Agriculture',
    'Camping',
    'Climbing',
    'Environment',
    'Forestry',
    'Hiking',
    'Nature',
    'Outdoors',
    'Scouting',
    'Survivalist',
    'Advertising',
    'Architecture',
    'C.A.D.',
    'Computer Graphics',
    'Design',
    'Desktop Publishing',
    'Graphic Design',
    'Industrial Design',
    'Photoshop',
    'Art History',
    'Arts',
    'Drawing',
    'Fine Arts',
    'Painting',
    'Photography',
    'Postmodernism',
    'Sculpting',
    'Ballet',
    'Dancing',
    'Live Theatre',
    'Musicals',
    'Performing Arts',
    'Business',
    'Career planning',
    'Consumer Info',
    'Entrepreneurship',
    'Home Business',
    'Management/HR',
    'Marketing',
    'Continuing Education',
    'Education',
    'Homeschooling',
    'Library Resources',
    'Research',
    'Self Improvement',
    'University/College',
    'Accounting',
    'Banking',
    'Capitalism',
    'Daytrading',
    'Economics',
    'Financial planning',
    'Insurance',
    'Investing',
    'Mutual Funds',
    'Options/Futures',
    'Real Estate',
    'Taxation',
    'Antiques',
    'Christmas',
    'Collecting',
    'Crafts',
    'Crochet',
    'Dolls/Puppets',
    'Knitting',
    'Memorabilia',
    'Quilting',
    'Scrapbooking',
    'Sewing',
    'Woodworking',
    'Bargains/Coupons',
    'Beauty',
    'Clothing',
    'Ecommerce',
    'Fashion',
    'Jewelry',
    'Shopping',
    'Anatomy',
    'Biomechanics',
    'Biotech',
    'Cognitive Science',
    'Evolution',
    'Genetics',
    'Microbiology',
    'Neuroscience',
    'Pharmacology',
    'Physiology',
    'AIDS',
    'Aging',
    'Arthritis',
    'Asthma',
    'Brain Disorders',
    'Cancer',
    'Diabetes',
    'Disabilities',
    'Eating Disorders',
    'Glaucoma',
    'Heart Conditions',
    'Learning Disorders',
    'Substance Abuse',
    'Alternative Health',
    'Antiaging',
    'Dentistry',
    'Doctors/Surgeons',
    'Ergonomics',
    'Health',
    'Kinesiology',
    'Medical Science',
    'Mental Health',
    'Nursing',
    'Physical Therapy',
    'Psychiatry',
    'Psychology',
    'Sexual Health',
    'Weight Loss',
    'Alternative News',
    'Bisexual Culture',
    'Conspiracies',
    'Counterculture',
    'Crime',
    'Drugs',
    'Forensics',
    'Gay Culture',
    'Goth Culture',
    'Hedonism',
    'Lefthanded',
    'Lesbian Culture',
    'Paranormal',
    'Subculture',
    'Tattoos/Piercing',
    'American History',
    'Ancient History',
    'Anthropology',
    'Archaeology',
    'Classical Studies',
    'Cold War',
    'History',
    'Medieval History',
    'Philosophy',
    'Africa',
    'African Americans',
    'Asia',
    'Australia',
    'Brazil',
    'Canada',
    'Caribbean',
    'Central America',
    'China',
    'Culture/Ethnicity',
    'Eastern Studies',
    'Europe',
    'France',
    'Geography',
    'Germany',
    'India',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Japan',
    'Korea',
    'Linguistics',
    'Mexico',
    'Middle East',
    'Native Americans',
    'Netherlands',
    'New York',
    'Oceania',
    'Russia',
    'South America',
    'Spain',
    'Terrorism',
    'UK',
    'USA',
    'Alcoholic Drinks',
    'Beer',
    'Beverages',
    'Cigars',
    'Coffee',
    'Food/Cooking',
    'Homebrewing',
    'Nutrition',
    'Restaurants',
    'Tea',
    'Vegetarian',
    'Wine',
    'Botany',
    'Construction',
    'Gardening',
    'Home Improvement',
    'Homemaking',
    'Interior Design',
    'Landscaping',
    'Restoration',
    'Hotels',
    'Luxury',
    'Nightlife',
    'Spas',
    'Travel',
    'Bizarre/Oddities',
    'Cyberculture',
    'Humor',
    'Satire',
    'American Lit.',
    'Biographies',
    'Books',
    'British Literature',
    "Children's Books",
    'Fantasy Books',
    'Humanities',
    'Journalism',
    'Literature',
    'Mystery Novels',
    'Poetry',
    'Quotes',
    'Romance Novels',
    'Shakespeare',
    'Writing',
    'Celtic Music',
    'Christian Music',
    'Classical Music',
    'Ethnic Music',
    'Gospel music',
    'Latin Music',
    'Lounge Music',
    'Opera',
    'Vocal Music',
    'Ambient Music',
    "DJ's/Mixing",
    'Dance Music',
    'Disco',
    "Drum'n'Bass",
    'Electronica/IDM',
    'House music',
    'Industrial Music',
    'Rave Culture',
    'Techno',
    'Trance',
    'TripHop/Downtempo',
    'Blues music',
    'Funk',
    'Jazz',
    'Oldies Music',
    'Reggae',
    'Soul/R&B',
    'Country music',
    'HipHop/Rap',
    'Karaoke',
    'Music',
    'Pop music',
    'Alternative Rock',
    'Britpop',
    'Classic Rock',
    'Folk music',
    'Heavy metal',
    'Indie Rock/Pop',
    'Punk Rock',
    'Rock music',
    'Guitar',
    'Music Composition',
    'Music Instruments',
    'Music Theory',
    'Musician Resources',
    'Percussion',
    'Radio Broadcasts',
    'Songwriting',
    'Activism',
    'Anarchism',
    'Communism',
    'Feminism',
    'Law',
    'Liberties/Rights',
    'Military',
    'News(General)',
    'Socialism',
    'Sociology',
    'Ethics',
    'Humanitarianism',
    "Int'l Development",
    'Nonprofit/Charity',
    'Conservative Politics',
    'Government',
    'Liberal Politics',
    'Political Science',
    'Politics',
    'Babies',
    'Divorce',
    'Entertaining Guests',
    'Family',
    'For Kids',
    'Genealogy',
    'Kids',
    'Married Life',
    'Parenting',
    'Pregnancy/Birth',
    'Senior Citizens',
    'Teen Life',
    'Teen Parenting',
    'Dating Tips',
    'Matchmaking',
    "Men's Issues",
    'Relationships',
    'Weddings',
    "Women's Issues",
    'Atheist/Agnostic',
    'Buddhism',
    'Catholic',
    'Christianity',
    'Hinduism',
    'Islam',
    'Judaism',
    'Mormon',
    'Orthodox',
    'Paganism',
    'Protestant',
    'Religion',
    'Scientology',
    'Sufism',
    'Sunni',
    'Wicca',
    'Astrology/Psychics',
    'Mythology',
    'New Age',
    'Spirituality',
    'Ecology',
    'Geoscience',
    'Marine Biology',
    'Meteorology',
    'Paleontology',
    'Zoology',
    'Alternative Energy',
    'Energy Industry',
    'Mining/Metallurgy',
    'Nuclear Science',
    'Petroleum',
    'Chemical Eng.',
    'Civil Engineering',
    'Electrical Eng.',
    'Machinery',
    'Manufacturing',
    'Mechanical Eng.',
    'Chaos/Complexity',
    'Logic',
    'Mathematics',
    'Statistics',
    'Biology',
    'Chemistry',
    'Physics',
    'Science',
    'Astronomy',
    'Space Exploration',
    'UFOs',
    'Aviation/Aerospace',
    'Car Parts',
    'Cars',
    'Motor Sports',
    'Motorcycles',
    'Trains/Railroads',
    'Transportation',
    'Vintage Cars',
    'Extreme Sports',
    'Skateboarding',
    'Skiing',
    'Skydiving',
    'Snowboarding',
    'Surfing',
    'Water Sports',
    'Windsurfing',
    'Billiards',
    'Board Games',
    'Card Games',
    'Chess',
    'Gambling',
    'Magic/Illusions',
    'Online Games',
    'Poker',
    'Puzzles',
    'Quizzes',
    'Roleplaying Games',
    'Toys',
    'Video Games',
    'Boating',
    'Bowling',
    'Canoeing/Kayaking',
    'Fishing',
    'Flyfishing',
    'Golf',
    'Guns',
    'Hunting',
    'Sailing',
    'Scuba Diving',
    'American Football',
    'Badminton',
    'Baseball',
    'Basketball',
    'Bicycling',
    'Bodybuilding',
    'Boxing',
    'Cheerleading',
    'Cricket',
    'Equestrian/Horses',
    'Figure Skating',
    'Fitness',
    'Gymnastics',
    'Hockey',
    'Martial Arts',
    'Racquetball',
    'Rodeo',
    'Rugby',
    'Running',
    'Soccer',
    'Sports(General)',
    'Squash',
    'Swimming',
    'Tennis',
    'Track/Field',
    'Volleyball',
    'Wrestling',
    'Yoga',
    'Animation',
    'Anime',
    'Cartoons',
    'Comic Books',
    'Multimedia',
    'Acting',
    'Action Movies',
    'Babes',
    'Celebrities',
    'Classic Films',
    'Comedy Movies',
    'Cult Films',
    'Drama Movies',
    'Film Noir',
    'Filmmaking',
    'Foreign Films',
    'Horror Movies',
    'Independent Film',
    'Movies',
    'Science Fiction',
    'Soap Operas',
    'Soundtracks',
    'Television',
    'A.I.',
    'Futurism',
    'Nanotech',
    'Robotics',
    'Semiconductors',
    'Supercomputing',
    'Virtual Reality',
    'Computer Science',
    'Databases',
    'Embedded Systems',
    'Encryption',
    'Hacking',
    'Java',
    'Open Source',
    'PHP',
    'Perl',
    'Programming',
    'Shareware',
    'Software',
    'Web Development',
    'Windows Dev',
    'Amateur Radio',
    'Audio Equipment',
    'Cell Phones',
    'Electronic Devices',
    'Electronic Parts',
    'Gadgets',
    'Ipod',
    'Mobile Computing',
    'Peripheral Devices',
    'Photo Gear',
    'Recording Gear',
    'Technology',
    'Telecom',
    'Video Equipment',
    'Computer Hardware',
    'Computer Security',
    'Computers',
    'IT',
    'Linux/Unix',
    'MacOS',
    'Network Security',
    'Operating Systems',
    'Proxy',
    'Windows',
    'Sleeping',
    'Sex',
]
