import * as admin from 'firebase-admin';

admin.initializeApp();

export const db = admin.firestore();
export const fcm = admin.messaging();

export const userProfilesRef = db.collection('user_profiles');
export const usersPrivateInfoRef = db.collection('users_private_info');
export const usersAlgorithmDataRef = db.collection('users_algorithm_data');
export const userStatusesRef = db.collection('user_statuses');
export const chatsRef = db.collection('chats');

export const numInterestGroups = 52;
export const interestsToGroupNo: Record<string, number> = {
  Animals: 0,
  'Bird Watching': 0,
  Birds: 0,
  Cats: 0,
  Dogs: 0,
  'Exotic Pets': 0,
  Fish: 0,
  Pets: 0,
  Agriculture: 1,
  Camping: 1,
  Climbing: 1,
  Environment: 1,
  Forestry: 1,
  Hiking: 1,
  Nature: 1,
  Outdoors: 1,
  Scouting: 1,
  Survivalist: 1,
  Advertising: 2,
  Architecture: 2,
  'C.A.D.': 2,
  'Computer Graphics': 2,
  Design: 2,
  'Desktop Publishing': 2,
  'Graphic Design': 2,
  'Industrial Design': 2,
  Photoshop: 2,
  'Art History': 3,
  Arts: 3,
  Drawing: 3,
  'Fine Arts': 3,
  Painting: 3,
  Photography: 3,
  Postmodernism: 3,
  Sculpting: 3,
  Ballet: 4,
  Dancing: 4,
  'Live Theatre': 4,
  Musicals: 4,
  'Performing Arts': 4,
  Business: 5,
  'Career planning': 5,
  'Consumer Info': 5,
  Entrepreneurship: 5,
  'Home Business': 5,
  'Management/HR': 5,
  Marketing: 5,
  'Continuing Education': 6,
  Education: 6,
  Homeschooling: 6,
  'Library Resources': 6,
  Research: 6,
  'Self Improvement': 6,
  'University/College': 6,
  Accounting: 7,
  Banking: 7,
  Capitalism: 7,
  Daytrading: 7,
  Economics: 7,
  'Financial planning': 7,
  Insurance: 7,
  Investing: 7,
  'Mutual Funds': 7,
  'Options/Futures': 7,
  'Real Estate': 7,
  Taxation: 7,
  Antiques: 8,
  Christmas: 8,
  Collecting: 8,
  Crafts: 8,
  Crochet: 8,
  'Dolls/Puppets': 8,
  Knitting: 8,
  Memorabilia: 8,
  Quilting: 8,
  Scrapbooking: 8,
  Sewing: 8,
  Woodworking: 8,
  'Bargains/Coupons': 9,
  Beauty: 9,
  Clothing: 9,
  Ecommerce: 9,
  Fashion: 9,
  Jewelry: 9,
  Shopping: 9,
  Anatomy: 10,
  Biomechanics: 10,
  Biotech: 10,
  'Cognitive Science': 10,
  Evolution: 10,
  Genetics: 10,
  Microbiology: 10,
  Neuroscience: 10,
  Pharmacology: 10,
  Physiology: 10,
  AIDS: 11,
  Aging: 11,
  Arthritis: 11,
  Asthma: 11,
  'Brain Disorders': 11,
  Cancer: 11,
  Diabetes: 11,
  Disabilities: 11,
  'Eating Disorders': 11,
  Glaucoma: 11,
  'Heart Conditions': 11,
  'Learning Disorders': 11,
  'Substance Abuse': 11,
  'Alternative Health': 12,
  Antiaging: 12,
  Dentistry: 12,
  'Doctors/Surgeons': 12,
  Ergonomics: 12,
  Health: 12,
  Kinesiology: 12,
  'Medical Science': 12,
  'Mental Health': 12,
  Nursing: 12,
  'Physical Therapy': 12,
  Psychiatry: 12,
  Psychology: 12,
  'Sexual Health': 12,
  'Weight Loss': 12,
  'Alternative News': 13,
  'Bisexual Culture': 13,
  Conspiracies: 13,
  Counterculture: 13,
  Crime: 13,
  Drugs: 13,
  Forensics: 13,
  'Gay Culture': 13,
  'Goth Culture': 13,
  Hedonism: 13,
  Lefthanded: 13,
  'Lesbian Culture': 13,
  Paranormal: 13,
  Subculture: 13,
  'Tattoos/Piercing': 13,
  'American History': 14,
  'Ancient History': 14,
  Anthropology: 14,
  Archaeology: 14,
  'Classical Studies': 14,
  'Cold War': 14,
  History: 14,
  'Medieval History': 14,
  Philosophy: 14,
  Africa: 15,
  'African Americans': 15,
  Asia: 15,
  Australia: 15,
  Brazil: 15,
  Canada: 15,
  Caribbean: 15,
  'Central America': 15,
  China: 15,
  'Culture/Ethnicity': 15,
  'Eastern Studies': 15,
  Europe: 15,
  France: 15,
  Geography: 15,
  Germany: 15,
  India: 15,
  Iraq: 15,
  Ireland: 15,
  Israel: 15,
  Italy: 15,
  Japan: 15,
  Korea: 15,
  Linguistics: 15,
  Mexico: 15,
  'Middle East': 15,
  'Native Americans': 15,
  Netherlands: 15,
  'New York': 15,
  Oceania: 15,
  Russia: 15,
  'South America': 15,
  Spain: 15,
  Terrorism: 15,
  UK: 15,
  USA: 15,
  'Alcoholic Drinks': 16,
  Beer: 16,
  Beverages: 16,
  Cigars: 16,
  Coffee: 16,
  'Food/Cooking': 16,
  Homebrewing: 16,
  Nutrition: 16,
  Restaurants: 16,
  Tea: 16,
  Vegetarian: 16,
  Wine: 16,
  Botany: 17,
  Construction: 17,
  Gardening: 17,
  'Home Improvement': 17,
  Homemaking: 17,
  'Interior Design': 17,
  Landscaping: 17,
  Restoration: 17,
  Hotels: 18,
  Luxury: 18,
  Nightlife: 18,
  Spas: 18,
  Travel: 18,
  'Bizarre/Oddities': 19,
  Cyberculture: 19,
  Humor: 19,
  Satire: 19,
  'American Lit.': 20,
  Biographies: 20,
  Books: 20,
  'British Literature': 20,
  "Children's Books": 20,
  'Fantasy Books': 20,
  Humanities: 20,
  Journalism: 20,
  Literature: 20,
  'Mystery Novels': 20,
  Poetry: 20,
  Quotes: 20,
  'Romance Novels': 20,
  Shakespeare: 20,
  Writing: 20,
  'Celtic Music': 21,
  'Christian Music': 21,
  'Classical Music': 21,
  'Ethnic Music': 21,
  'Gospel music': 21,
  'Latin Music': 21,
  'Lounge Music': 21,
  Opera: 21,
  'Vocal Music': 21,
  'Ambient Music': 22,
  "DJ's/Mixing": 22,
  'Dance Music': 22,
  Disco: 22,
  "Drum'n'Bass": 22,
  'Electronica/IDM': 22,
  'House music': 22,
  'Industrial Music': 22,
  'Rave Culture': 22,
  Techno: 22,
  Trance: 22,
  'TripHop/Downtempo': 22,
  'Blues music': 23,
  Funk: 23,
  Jazz: 23,
  'Oldies Music': 23,
  Reggae: 23,
  'Soul/R&B': 23,
  'Country music': 24,
  'HipHop/Rap': 24,
  Karaoke: 24,
  Music: 24,
  'Pop music': 24,
  'Alternative Rock': 25,
  Britpop: 25,
  'Classic Rock': 25,
  'Folk music': 25,
  'Heavy metal': 25,
  'Indie Rock/Pop': 25,
  'Punk Rock': 25,
  'Rock music': 25,
  Guitar: 26,
  'Music Composition': 26,
  'Music Instruments': 26,
  'Music Theory': 26,
  'Musician Resources': 26,
  Percussion: 26,
  'Radio Broadcasts': 26,
  Songwriting: 26,
  Activism: 27,
  Anarchism: 27,
  Communism: 27,
  Feminism: 27,
  Law: 27,
  'Liberties/Rights': 27,
  Military: 27,
  'News(General)': 27,
  Socialism: 27,
  Sociology: 27,
  Ethics: 28,
  Humanitarianism: 28,
  "Int'l Development": 28,
  'Nonprofit/Charity': 28,
  'Conservative Politics': 29,
  Government: 29,
  'Liberal Politics': 29,
  'Political Science': 29,
  Politics: 29,
  Babies: 30,
  Divorce: 30,
  'Entertaining Guests': 30,
  Family: 30,
  'For Kids': 30,
  Genealogy: 30,
  Kids: 30,
  'Married Life': 30,
  Parenting: 30,
  'Pregnancy/Birth': 30,
  'Senior Citizens': 30,
  'Teen Life': 30,
  'Teen Parenting': 30,
  'Dating Tips': 31,
  Matchmaking: 31,
  "Men's Issues": 31,
  Relationships: 31,
  Weddings: 31,
  "Women's Issues": 31,
  'Atheist/Agnostic': 32,
  Buddhism: 32,
  Catholic: 32,
  Christianity: 32,
  Hinduism: 32,
  Islam: 32,
  Judaism: 32,
  Mormon: 32,
  Orthodox: 32,
  Paganism: 32,
  Protestant: 32,
  Religion: 32,
  Scientology: 32,
  Sufism: 32,
  Sunni: 32,
  Wicca: 32,
  'Astrology/Psychics': 33,
  Mythology: 33,
  'New Age': 33,
  Spirituality: 33,
  Ecology: 34,
  Geoscience: 34,
  'Marine Biology': 34,
  Meteorology: 34,
  Paleontology: 34,
  Zoology: 34,
  'Alternative Energy': 35,
  'Energy Industry': 35,
  'Mining/Metallurgy': 35,
  'Nuclear Science': 35,
  Petroleum: 35,
  'Chemical Eng.': 36,
  'Civil Engineering': 36,
  'Electrical Eng.': 36,
  Machinery: 36,
  Manufacturing: 36,
  'Mechanical Eng.': 36,
  'Chaos/Complexity': 37,
  Logic: 37,
  Mathematics: 37,
  Statistics: 37,
  Biology: 38,
  Chemistry: 38,
  Physics: 38,
  Science: 38,
  Astronomy: 39,
  'Space Exploration': 39,
  UFOs: 39,
  'Aviation/Aerospace': 40,
  'Car Parts': 40,
  Cars: 40,
  'Motor Sports': 40,
  Motorcycles: 40,
  'Trains/Railroads': 40,
  Transportation: 40,
  'Vintage Cars': 40,
  'Extreme Sports': 41,
  Skateboarding: 41,
  Skiing: 41,
  Skydiving: 41,
  Snowboarding: 41,
  Surfing: 41,
  'Water Sports': 41,
  Windsurfing: 41,
  Billiards: 42,
  'Board Games': 42,
  'Card Games': 42,
  Chess: 42,
  Gambling: 42,
  'Magic/Illusions': 42,
  'Online Games': 42,
  Poker: 42,
  Puzzles: 42,
  Quizzes: 42,
  'Roleplaying Games': 42,
  Toys: 42,
  'Video Games': 42,
  Boating: 43,
  Bowling: 43,
  'Canoeing/Kayaking': 43,
  Fishing: 43,
  Flyfishing: 43,
  Golf: 43,
  Guns: 43,
  Hunting: 43,
  Sailing: 43,
  'Scuba Diving': 43,
  'American Football': 44,
  Badminton: 44,
  Baseball: 44,
  Basketball: 44,
  Bicycling: 44,
  Bodybuilding: 44,
  Boxing: 44,
  Cheerleading: 44,
  Cricket: 44,
  'Equestrian/Horses': 44,
  'Figure Skating': 44,
  Fitness: 44,
  Gymnastics: 44,
  Hockey: 44,
  'Martial Arts': 44,
  Racquetball: 44,
  Rodeo: 44,
  Rugby: 44,
  Running: 44,
  Soccer: 44,
  'Sports(General)': 44,
  Squash: 44,
  Swimming: 44,
  Tennis: 44,
  'Track/Field': 44,
  Volleyball: 44,
  Wrestling: 44,
  Yoga: 44,
  Animation: 45,
  Anime: 45,
  Cartoons: 45,
  'Comic Books': 45,
  Multimedia: 45,
  Acting: 46,
  'Action Movies': 46,
  Babes: 46,
  Celebrities: 46,
  'Classic Films': 46,
  'Comedy Movies': 46,
  'Cult Films': 46,
  'Drama Movies': 46,
  'Film Noir': 46,
  Filmmaking: 46,
  'Foreign Films': 46,
  'Horror Movies': 46,
  'Independent Film': 46,
  Movies: 46,
  'Science Fiction': 46,
  'Soap Operas': 46,
  Soundtracks: 46,
  Television: 46,
  'A.I.': 47,
  Futurism: 47,
  Nanotech: 47,
  Robotics: 47,
  Semiconductors: 47,
  Supercomputing: 47,
  'Virtual Reality': 47,
  'Computer Science': 48,
  Databases: 48,
  'Embedded Systems': 48,
  Encryption: 48,
  Hacking: 48,
  Java: 48,
  'Open Source': 48,
  PHP: 48,
  Perl: 48,
  Programming: 48,
  Shareware: 48,
  Software: 48,
  'Web Development': 48,
  'Windows Dev': 48,
  'Amateur Radio': 49,
  'Audio Equipment': 49,
  'Cell Phones': 49,
  'Electronic Devices': 49,
  'Electronic Parts': 49,
  Gadgets: 49,
  Ipod: 49,
  'Mobile Computing': 49,
  'Peripheral Devices': 49,
  'Photo Gear': 49,
  'Recording Gear': 49,
  Technology: 49,
  Telecom: 49,
  'Video Equipment': 49,
  'Computer Hardware': 50,
  'Computer Security': 50,
  Computers: 50,
  IT: 50,
  'Linux/Unix': 50,
  MacOS: 50,
  'Network Security': 50,
  'Operating Systems': 50,
  Proxy: 50,
  Windows: 50,
  Sleeping: 51,
  Sex: 51,
};
export const interestsList = Object.keys(interestsToGroupNo);
